:sparkles: Feat: AIDetail, community router
LikeLion-at-DGU/moin_frontend pull request #10
Opened 2023-08-01 05:24 UTC by shimseohyun

- AiServiceList에서 Detail로 이동
- 상단 네브바의 Community에서 Suggestion으로 이동

전부 임시적으로 만들어 둔거라 구체적인 이동이나, state 전달은 Figma가 나와야할 것 같습니다... 🥹

2023-08-01 07:43 UTC, seochan99 requested changes
1. html태그는 jsx에서 안쓰는걸 습관화합시다
2. 인라인 스타일도 왠만하면 빠이!

2023-08-01 07:43 UTC, seochan99 commented on src/components/main/mainCard/MainCard.jsx
> +  return <div>MainCard</div>;
얘네 왜 다 들어가지?

2023-08-01 07:43 UTC, seochan99 commented on src/components/main/mainSearch/MainSearch.jsx
> +  return <div>MainSearch</div>;
얘도 div가 들어가네

2023-08-01 07:43 UTC, seochan99 commented on src/main.jsx
> +import router from "./Router"
얘는 왜 매번 바뀌2ㅣ @ZZZINU ??

2023-08-01 07:43 UTC, seochan99 commented on src/pages/ai/AiServiceList.jsx
> +      <div style={{padding:'10px'}}>AiServiceList</div>
으아아아아가가악

안돼!!! 절대로 이렇게 작성하지막!!!!!!!
jsx코드에 html있을때마다 1커밋 추가시킬꺼야 ㅡ ㅡ

인라인 스타일도 절 대 지 양 !!!!

2023-08-01 07:43 UTC, seochan99 commented on src/pages/community/Community.jsx
> +      <div>커뮤니티(아직페이지없음...)</div>
div멈춰!

2023-08-01 08:24 UTC, shimseohyun commented on src/main.jsx
> +import router from "./Router"
그러게요 풀받을때마다 에러떠서 바꾸긴 했어요. 일단 ./Router로  진행할게요!

2023-08-02 05:02 UTC, ZZZINU commented on src/main.jsx
> +import router from "./Router"
오잉 에러나서 바꿨는데 내 코드가 이상한가 나중에 한번 봐주세요

2023-08-02 05:15 UTC, ZZZINU approved these changes

2023-08-02 05:15 UTC, ZZZINU commented on src/components/main/mainBanner/Banner.jsx
> +      <>banner</>
확인했습니다

2023-08-02 05:15 UTC, ZZZINU commented on src/pages/main/Main.jsx
> +      <MainBannerList />
수고하셨습니다 👍

2023-08-02 05:15 UTC, ZZZINU commented on src/components/main/mainBanner/Banner.jsx
> +      <>banner1</>
banner 컴포넌트 생성/추가는 같은건감..?

2023-08-02 05:47 UTC, seochan99 approved these changes

2023-08-02 05:48 UTC, merged